bbc/lrud

- package-lock.json
- src/index.js
- test/lrud.test.js
Primarily for use in https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-7307
Calling an `unregister` then `register` causes the array of nodes to lose index - this causes a problem for us, where we are effectively wanting to replace an entire node, while keeping its position inside the array the same.
My working solution is to remove all the children from the node, and then replace the node directly without removing it first. This has proven to work in practice (for our use case at least) where we are running a collection of nodes through `upsert`. Any current matching ones with children have their children removed, and new children added via `register` with a parent, otherwise the new nodes are added.
I've written some tests too, but we are having issues running the test suite locally ☹️ …
> Added `upsert` function & tests

- README.md
- src/index.js
_Taken from the new FAQ_
> Q: All my parents have orientations, everything is setup in the navigation tree, and I STILL can't focus on the element.
A: A node is considered invalid if it has 0 children AND no `selectAction` AND no orientation. 
Make sure a node has at least 1 child, or a select action, or an orientation if you want it to be focusable. 
This work ensures the above
> Block movement to invalid nodes

- docs/ADRs/ADR-001-navigation-overrides.md
- src/index.js
- test/lrud.test.js
https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-8378
Work done by @benwdev and myself
We're introducing an "overrides" concept into LRUD.
The idea is contrary to a navigation tree, but we have a ton of scenarios whereby we need to jump between different nodes for specific behaviour as given by UX/Product, and this is a clean way to handle that.
Furthermore, because the overrides exist on the same level as navigation nodes but separate, they can be changed at runtime based on app state.
See tests for implementation usage
- `overrides` object so that each override can be named
- ADR explaining logic and reasoning
> IPLAYERTV 8378 - LRUD Overrides

- .gitignore
- README.md
- src/index.js
- test/lrud.test.js
https://jira.dev.bbc.co.uk/browse/IPLAYERTVV1-8416
LRUD is currently is not firing correct `move` object data for an `onMove` event, when the move was completed via an override.
This piece of work is to ensure the data for an `onMove` callback is as correct as can be.
- updated readme
- added tests
Ensure the move object contains the correct;
- id
- enter id and index
- leave id and index
- parent
- children
> IPLAYERTVV1-8416 Updates to overrides system

- docs/usage.md
- src/index.ts
- src/unregister.test.js
Fixes https://github.com/bbc/lrud/issues/8
When we unregister a node, if its the root node, actually just clear the tree (and associated state) out. the root node is the only node that could ever _not_ have a parent, so handles that as well.
Changelog
- if unregistering the root node, simple reset the tree and overrides
- comment in readme
- new test
- I ran a format and fixed a bunch of indentations
> [Issue 8] Handle unregistering of root node

- src/index.ts
- src/register.test.js
Fixes #9 
When registering a node with an ID, if that ID already exists in the tree, throw an exception.
Changelog
- new behaviour to throw an exception
- new test
> Error when registering an existing node

- src/index.ts
- src/unregister.test.js
Fixes #11 
Handles unregistering a node if there are no other nodes to focus on
Changelog
- only perform the "...and focus on something else" part of the process if we can find a `top` from the parent node of the thing we're unregistering
- tests
> Handle unregistering a node leaving no focusable node

- package-lock.json
- package.json
- src/index.ts
- src/interfaces.ts
- src/multiple-instance-interaction.test.js
Using Lrud in engineering spikes has revealed a clear and definite desire for the ability to take an LRUD tree as raw JSON data, and to register that entire tree against a different LRUD instance.
Basically, a smart clone of an Lrud tree.
New tests added in `src/multiple-instance-interaction.test.js`
> [Feature] register a tree into an instance (& misc. fixes)

- docs/usage.md
- src/index.ts
- src/insert-tree.test.js
- src/interfaces.ts
- src/unregister.test.js
- src/utils.test.js
- src/utils.ts
Feature to support the insertion of a partial LRUD tree in JSON form into an existing LRUD instance.
In order to support the use cases we want, the engineering spike at https://github.com/bbc/ssr-refactor-spike surfaced a desire to be able to easily insert partial navigation trees, as per the trees that would come down from an SSR response.
This PR includes that behaviour and tests around it.
Tested locally using https://github.com/bbc/ssr-refactor-spike and new test files
> [Feature] Partial tree insertion

- src/index.ts
When we're unregistering a node, we should turn off `isIndexAlignMode` if we're unregistering something we're focused on.
This makes the behaviour of "find the last prev thing you CAN focus on" a lot more natural and easy to understand from a user P.O.V
Realised this behaviour seems very odd and counter-intuitive when using LRUD in the TTR spike.
> [Fix] Turn off `isIndexAlignMode` when unregistering a focused node

- src/index.ts
- src/unregister.test.js
When unregistering the root node, the tree is now effectively empty, so reset all relevant state.
Issue was raised that noticed if the root node had children and was then unregistered, if it was re-registered with the same name it could cause the unregistered children to come back.
Fixes #19 
This was due to internal pathing state.
New test case for the supplied reproduction scenario in #19
> [Fix] When unregistering the root node, reset all relevant instance state.

- src/index.ts
- src/unregister.test.js
We had some wonky logic around string matching when handling internal pathing.
This has been fixed.
Fixes #21 
New tests
> [Fix] Fixing logic around string matching and new tests

- docs/usage.md
- src/index.ts
- src/interfaces.ts
- src/unregister.test.js
A new config object is given to `unregisterNode()`. One of these options, `forceRefocus` will make LRUD find a new node to focus on if unregistering the currently focused node.
To match current behaviour, `forceRefocus` defaults to true.
Also fixes an underlying refocus on unregister issue.
Suggested by https://github.com/bbc/lrud/issues/23
Agree in principle - there are simply some scenarios where LRUD will not be able find a good fit to focus on. In this case, the developer should call `assignFocus` after `unregisterNode` in API-land.
New unit tests
> [Feature] Unregister options

- src/events.test.js
- src/index.ts
- src/interfaces.ts
"select" events should be emitted without `onSelect` being required.
Fixes #27 
New unit tests
> [Fix] Fix onSelect and "select" event emission

- src/focus-on-empty-node.test.js
- src/index.ts
- src/interfaces.ts
Ensures 2 things happen
- if assigning focus to a node with children, but 0 focusable children, throw an exception
- if digging down from a node that is not focusable, and has 0 focusable children, instead dig down from its next sibling
This ensures that actions that would result in focus trying to be set on something invalid either don't happen, or can be caught properly.
I've also done minor fixes in place around typescript
- added return type to `getNode()`
- added types to interface for node
Fixes #26 
New unit tests
> [Fix] Assigning focus, and moving over/to branches without focusable children

- docs/usage.md
- src/utils.test.js
- src/utils.ts
Solidifies the interaction between `selectAction` and `isFocusable` properties on a node to enforce that when a node has `isFocusable: false` it will not be focusable, regardless of the presence of a `selectAction` property.
This change makes it easier to have buttons where the focusability can be changed without having to remove and re-add the `selectAction`.
Added an automated test to the `utils` file to ensure this behaves as expected.
> isFocusable overrides selectAction presence

- docs/usage.md
- src/index.ts
- src/lrud.test.js
Adds an `setNodeFocusable` function to change the isFocusable state of a node.
Also moves the functionality for recalculating focus from `unregisterNode` into a shared function so the same process can be used for unfocusing and removing a node.
Need a way of updating the tree to allow changes in state, IE: a button that was previously disabled becoming enabled. Could do this by completely regenerating the tree and replacing in place but that loses any changes to the state of the tree and the active focus states.
Split from larger PR due to feedback: https://github.com/bbc/lrud/pull/38#issuecomment-547454172
Added automated tests.
> Added feature to change focusability of a node

- src/index-align.test.js
- src/lrud.test.js
- src/utils.test.js
- src/utils.ts
Fixed a bug where moving to a row where the equivalent index is unfocusable would throw an error
Example of bug
```
[] indicates focus
() indicates unfocusableness
[a] b c d
(e) f g h
Press down
expected result:
a   b  c d
(e) [f] g h
actual result
[a] b c d
(e) f g h
(Plus a type error)
```
Wrote automated tests, then manually tested on a layout.
> Fixed bug with moving to a row containing unfocusable items

- src/index.ts
- src/lrud.test.js
Altered method used by digDown to get its next child by not mutating the parent.
Previously this meant that you could end up "half-focusing" a non-focusable element.
Fixes: https://github.com/bbc/lrud/issues/41
Automated testing + manual testing
> Fixed bug where `digDown` sets a unfocusable node to be a parent's activeChild

- src/index.ts
- src/lrud.test.js
Fix the sorting  for the methods `getNodeFirstChild` and `getNodeLastChild`
Fixes #34 
- added callback for the call of the sort for the methods `getNodeFirstChild` and `getNodeLastChild`
We use the function `sort` with the methods `reindexChildrenOfNode`, `getNodeFirstChild` and `getNodeLastChild` to sort based on a numeric index.
Currently the sort for `getNodeFirstChild` and `getNodeLastChild` is used without a proper callback, making the sort to be based on string and not numbers causing a wrong sorting.
unit tests
N/A
> [issue 34] Fix call of the method sort with array of numbers

- src/utils.ts
Replace ES6 string functions with ES5 equivalent methods.
We target ES5 with LRUD's build but do not include any string polyfills so we're outputting invalid ES5
Automated tests
> Replace es6 string functions with es5 equivalents

- src/index.ts
- src/utils.ts
Replaces String.prototype.includes,endswith and Array.prototype.find.
We deploy to ES5 devices but this code does not get polyfilled or transpiled.
Automated testing.
> Replace uses of ES6 functions with ES5.

- docs/recipes.md
Headings 2 and 4 were displaying as "## Recipe 2..." for some reason. Deleting and re-typing the hashes seems to fix it.
Make them display as `<h2>` tags.
Markdown Preview in VSCode.
> Make headings 2 and 4 display correctly

- src/interfaces.ts
Make keyCode optional in KeyEvent interface. The code falls back to direction if none is provided anyway. See [src/index.ts Line 631](https://github.com/bbc/lrud/blob/master/src/index.ts#L631).
Closes https://github.com/bbc/lrud/issues/65.
I ran `npm test`. I'd appreciate advice on how this might impact other users of LRUD though.
> Make keyCode optional in KeyEvent interface

- src/events.test.js
- src/index.ts
When registering a node that is the first child, emit an 'active' event from index.ts.
Gives consistency between assigning focus and registering a node.
Updated existing tests to test new functionality.
> Emit active event when registering a node

- src/index.ts
- src/unregister.test.js
According to the docs: `unregisterOptions.forceRefocus if true, LRUD will attempt to re-focus on a new node if the currently focused node becomes unregistered due to the given node ID being unregistered`
This was not true, it always recalculated the focus regardless of if the focused node was actually removed, it also removed the focus completely even if the focused node wasn't removed.
This fixes #55 
If the focused node isn't removed there is no need to remove focus, the expected behavior I think is that focus remains if possible. The focus was also recalculated even if the focused node wasn't removed.
Tested in the application I've been building
Added a unit-test and modified a unit-test to be more precise.
> Fix(#55) focus removed when separate part of tree is removed

- src/index.ts
- src/lrud.test.js
This PR fixes node path resolution when given `nodeId` is not defined.
`getPathForNodeId` method didn't check whether provided `nodeId` is defined or not. As a result it was looking for node paths ending with `'.undefined'` or `'.null'`. If nodes with such ids exist then `climbUp` method was making infinite scan failing with `Maximum call stack size exceeded` error. When `root` node was reached, the climbing should stop, but instead `root`'s `undefined` parent was resolved as path to node with `'undefined'` id (string with 9 chars word) and climbing was continued until, again, `root` node was reached, and the story begins.
Having nodes with `'undefined'` or `'null'` ids is not common situation, and may point that similar bug (concatenating `null`/`undefined` variable with string) is …
> Fixing infinite climbUp, fixes #79

- src/index.ts
- src/unregister.test.js
This PR improves the process of unregistering the node.
Together with node all its children are automatically unregistered as well. In general the whole sub-tree, where the unregistered node is a top node, is unregistered.
Overrides have to be cleaned separately, because they are stored separately. This PR introduces more accurate check, which verifies does override relates not only to unregistered node but also to one of its children. 
#86
Fix was tested by unit tests and manually in app using LRUD library where such issue was found.
> Cleaning overrides of unregistered node and its children

- docs/usage.md
- src/index.ts
- src/insert-tree.test.js
- src/interfaces.ts
- src/lrud.test.js
- src/register.test.js
This PR fixes the way of checking if `index` property is defined and the way how index is calculated when registering the node.
Currently `index` property existence was simple verified be checking if such property is "truthy" or "falsy". For number it's wrong approach because '0' is "falsy", but on the other hand is a valid (defined) number.
It is also not possible to insert child at a given position. If given index value is already occupied by other child, than both children shares the same index value, which results in a bit weird behavior while searching for next or prev node. In such case the moment of registering takes precedence. To deal with that issue, the new property `isCoherentIndex ` is introduced. A node that has such property defined, keeps indices of its children coherent …
> Coherent way of maintaining the index value

- .gitignore
- docs/usage.md
- src/events.test.js
- src/focus-on-empty-node.test.js
- src/index.ts
- src/interfaces.ts
- src/lrud.test.js
- src/on-active-change.test.js
- src/register.test.js
- src/unregister.test.js
- src/utils.test.js
- src/utils.ts
This PR changes the way of marking the node as an `activeChild` of a parent node.
There’s a bunch of issues with moving focus over non-focusable nodes in more complicated (nested) scenarios. To solve them it was needed to change to way (and the moment) of setting the `activeChild` property. For the purpose of this PR it's worth to define a new term:
> *Focusable candidate* is a node that can accept the focus; it needs to be a focusable node or contains at least one child that is a focusable candidate
It's worth to explain here also, that:
> *Focusable node* is a node that has `isFocusable` property set to `true` or has `selectAction` property defined having `isFocusable` property not defined at the same time.
All of them occurs because of the way how `activeChild` property is picked. By …
> Improving the way of dealing with non-focusable nodes

- src/index.ts
- src/insert-tree.test.js
- src/lrud.test.js
- src/multiple-instance-interaction.test.js
- src/utils.test.js
- src/utils.ts
Library should gently handle wrong parameters provided to API methods simply by skipping such methods execution. This allows to keep navigation tree structure coherent and user's code not interrupted unexpectedly.
There might be cases that LRUD library exported methods may be used with inappropriate parameters. There's no any specific scenario. The `undefined` or `null` values can always happen. In such situations LRUD library should gently ignore them and skip method execution.
Library should provide coherent and error free API. There are many other places where not defined values are gently skipped, keeping the navigation tree structure coherent and user code not interrupted unexpectedly (usually by NPE). Such safe checks should be applied in all methods that are exported.
Tested by …
> Fail safely, null/undefined checks
